# Data sources

```{r}
library(ggplot2)
library(tidyverse)
library(patchwork)
library(ggnewscale)
library(foreign)
library(vcd)
library(ggmosaic)
#library(tigris)
library(ggalluvial)
library(dummies)
library(openxlsx)
#library(sf)
library(parcoords)
library(corrr)
library(rcompanion)
```

In this analyses, we use the following two kinds of datasets.

## American Trends Panel (ATP) by the Pew Research Center

https://www.pewresearch.org/american-trends-panel-datasets/

- Wave 33 (Apr 2018), Wave 55 (Oct 2019), and Wave 67 (Apr 2020)

The Pew Research Center has been conducting nationwide randomized surveys on social issues for many years. Questions related to environmental issues include:

- The climate change is due to human activities or just natural patterns in global climate.
- The federal government is doing too little for key aspects of the environment.
- We should decrease oil drilling/ coal mining.
- We should increase natural sources of electricity generations.
- We should increase nuclear power plants.

It also includes basic attributes of respondents such as age, sex, political party, region, education and income, which enables us to connect those basic attributes to their opinion.

The sample size is large enough (Wave 33: N=2541, Wave 55: N=3627, and Wave 67: N=10957), and so is the number of variables (all of them include 100+ questions). Since it has weights assigned to each sample in order to modify the imbalance of attributes of respondents compared to some benchmark sources such as *Gender 2017 American Community Survey*, we can present unbiased aggregated figures.

Climate change is a frequent topic in the ATP, so we can make comparison over time. (A note: since respondents to different surveys are not the same, it’s an aggregation of cross-sectional data instead of panel data.)

## US Election Data

https://www.fec.gov/introduction-campaign-finance/election-and-voting-information/

This is released by the Federal Election Commission and contains each state’s votes to each candidate in each federal election.

## How to answer the questions above using the data

- For question 1-4, we only use the data Wave 55 (Oct 2019), since we wanted to start with the latest dataset for the pre-pandemic USA.
We suspect that the pandemic has drastically changed a nature of environmental issues; i.e., 
they have the potential to bring a number of jobs to recover the economy rapidly.
Thus, the potentially more complicated analysis for the midst or post pandemic world remains for future study.

  - For question 1, the existing report above suggests the strong relationship between a party one supports and his/her opinion. Hence, we should control parties, when we conduct an analysis for this question. Here, this data is useful since we can calculate for each party whether there is a firm relationship of opinion toward each climate change issue with their incomes or educations.

  - For question 2, the existing report above suggests people living in the Pacific region are more likely to experience some climate change. Here, it is known that there are more Democrats in the Pacific region. Hence, we should control regions, when we conduct an analysis for this question. This is where this data comes in since for every region we can calculate the proportions of those who are recognizing that the climate change is affecting their community among each party, comparing the proportions of the two parties in each region. 

  - For question 1 and 2, we can also perform the statistical test of the difference of ratios.

  - For question 3, we can calculate and compare the proportions of Yes and No for each candidate factor such as sex, age, party, income and regions. We can also conduct the chi-squared t tests to add independent analyses.

  - For question 4, we will investigate the relationship between the average number of actions to protect environment and personalities (being organized or intellectual) for each strength of recognition of impact of global climate change on one's community.

- For question 5, we additionally use the US election (2018) data, Waves 33 and Wave 67. Since Waves 33 and Wave 67 are conducted on elections years, we can relate them with the outcomes of the elections. We can use a difference-in-difference method to check whether there's a correlation between the change in attitude towards climate change and the change in election outcomes. This is the **most original and promising one** in our EDVA analyses, since today "SDGs," "EGS" and other topics relating to environmental protection have become so popular that such matters can also affect the global economy and can even decide the winner or loser of national elections.
