# Data transformation

In this chapter, we briefly explain the data transformation process for exploratory analyses with R.

Since, the data is already well-formatted as .sav files, we only imported them into dataframes and only rendered some factor re-labeings or re-namings after analyzing the missing value patterns.

```{r}
df55 <- foreign::read.spss("./data/W55_Oct19/ATP W55.sav", to.data.frame=TRUE)
W55 = read.xlsx("./data/W55_Oct19/ATP W55 Weighted Resample.xlsx") %>% tibble()
W33 = read.xlsx("./data/W33_Mar18/ATP W33 Weighted Resample.xlsx") %>% tibble()
W67 = read.xlsx("./data/W67_May20/ATP W67 Weighted Resample.xlsx") %>% tibble()
```

Note that our data have weights which correct the potential bias of the attributes of the respondents of the questionnaires based on some other referenced large data. All the results in the existing report is based on those weights. Therefore, we should also consider those weights when we aggregate samples into graphs. However, for the following reasons, we employ simple aggregation for Question 1-3 (that is, just by simply counting the number of samples in the raw data, instead of aggregating the weights attached on the raw data).
Question 4-5 are based on the resampled dataset with n=100,000 by the method written below.

  - Many EDVA packages including those we used in this analyses cannot deal with data with weights. Hence, it requires quite additional work.
  
  - Although one way to overcome this is to resample the raw data with sampling probabilities proportional to those weights.
  However, it would fairly augment the raw data already not small (about from 4,000 to 10,000 rows with tens of columns for each dataset) if we try to ensure that the sampling error would be minimized, which was difficult for one of us due to the limited performance of his PC.
  
  - We have confirmed that there are no fatal discrepancies (that would change the conclusion) between the weighted aggregated results given in the existing report and our simply aggregated one given here.

  
