# Conclusion

We have investigated the relationship between individual attributes and attitudes towards environmental issues or political actions.
Main conclusions are the followings. One possible future task would be to conduct similar analyses for dataset of different countries where usual climate, recently experienced climate change, political structures, and culture can be all different. We could compare the result with one for US to derive the universal tendencies.:

- Q1 and Q3: Age, income, education, and sex are related with opinions on a wide range of environmental issues such as 
whether human activities contribute to global climate change or 
whether we should have more nuclear power uses.
The existence or the direction of impact can be intricately different (asymmetric) for each political party whose reasons are worth investigating further.
Policy makers should pay attention to these asymmetric tendencies when they are willing to pursue environmental policies by getting support from the large society.

- Q2: Republicans are not only likely to attribute climate change to just a natural phenomenon but also they are less likely to observe climate change affecting their communities in the first place.
Therefore, we should first review research regarding the existence of impact of climate change on our communities before we start discussing whether humans contributes to that climate change.

- Q4: Recognition of contribution of human activities to global climate change has a far larger effect than one's personality (being organized or intellectual) on how many actions one takes to protect environment, which suggests that policy makers should cultivate people's understandings if they want to pursue environmental protection.

- Q5: Environmental issues may have already been (and will be) highly influential to national elections in recent years (in the future).

