--- 
title: "Political views and their attributes"
author: "Zhenyu Yuan and Yuki Ikeda"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Recently, environmental issues such as SDGs or ESG are becoming more vital for our societies.
They are now important not just by scientific means but also from economic points of view and thus political points of view, too.
If we pursue to work on some environmental issue, we must have support from the large society and thus understand how people think of those issues, which is very challenging.
As an illustration, the world found that there was a wide range of opinion in USA regarding the global climate change, especially when the Tramp administration announced the withdrawal from Paris Agreement in 2017.
Considering a wide variety of US citizens who have different scientific, economic and political views,
it is worth exploring the existence of some relationship between attributes of individuals and their opinions to consider effective policies on environmental issues.
In this exploratory data analysis (EDVA), we want to deepen such kind of insights given in the report by the Pew Research Center:

https://www.pewresearch.org/science/2019/11/25/u-s-public-views-on-climate-and-energy/

Specifically, based on these analysis and the dataset, we work on the following questions.

1. Although the survey pointed out supported parties as a relevant factor, are educations or incomes also related to the opinion toward climate change issues (ex. whether the climate change is due to human activities or just natural patterns in global climate)? We address this issue upon trying to control other relevant effects such as supported parties.

2. From the survey, it is seen that Democrats are more likely to say that the federal government is doing too little for key aspects of the environment, and Democrats are more likely to think the climate change is due to human activities. With respect to this, are Democrats (Republicans) also more (less) recognizing that the climate changes are affecting their local communities (no matter what the reason of the change is) in the first place? We address this issue upon trying to control other relevant effects such as regions.

3. From the survey, it is seen that majority of people think that they should decrease the oil drilling or coal mining, and they should increase natural electricity generations such as one by wind or land heat. However, their opinion is separate with respect to whether they should increase the new clear power plants (Yes:49% vs No:49%). Here, how do factors (sex, age, party, income, regions,…) relate to the choice Yes and No.

4. The survey also includes some questions about the respondents’ personality such as being organized or intellectual. How is personality affecting one’s attitude towards climate changes and willingness to take actions to reduce climate change?

5. Has the public’s attitude towards climate change evolved over time? Does this change correlate with the change in election outcomes? Is it different across regions and groups?



